version: "3"
services:

  uvicorn:
    # ビルドするDockerfileのでディレクトリ相対パス
    build: ./fast_api
    # 指定したパスをコンテナにマウントする。"ホストのパス:コンテナのパス"となる
    volumes:
      - ./fast_api:/var/www/
      - ./${DATABASE_DIR}:/var/www/${DATABASE_DIR}
    # コンテナ内の環境変数を指定する
    env_file: .env
    environment:
      TZ: "Asia/Tokyo"

  https-portal:
    image: steveltn/https-portal:1
    # 解放するポートを指定。"ホスト:コンテナ"のマッピング となる
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./certs:/var/lib/https-portal
    environment:
      DOMAINS: ${DOMAIN_NAME} -> http://nginx
      STAGE: ${STAGE}
      TZ: "Asia/Tokyo"


  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # nginxのログをホストOSの /tmp/nginx_log に出力する
      - /tmp/nginx_log:/var/log/nginx
    links:
      - uvicorn
    environment:
      TZ: "Asia/Tokyo"

  twitter_bot:
    build: ./twitter_bot
    volumes:
      - ./twitter_bot:/opt/bot
      - ./${DATABASE_DIR}:/opt/bot/${DATABASE_DIR}
    env_file: .env
    environment:
      TZ: "Asia/Tokyo"